# Generated by Django 4.0.4 on 2022-04-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='blog.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like', to='blog.userprofile'),
        ),
    ]
