# Generated by Django 4.0.4 on 2022-05-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dislike',
            field=models.ManyToManyField(related_name='comment_dislikes', to='blog.userprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(related_name='comment_likes', to='blog.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(related_name='post_dislikes', to='blog.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='post_likes', to='blog.userprofile'),
        ),
    ]
