# Generated by Django 4.0.4 on 2022-04-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_dislike_comment_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slot',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
