# Generated by Django 4.0.4 on 2022-04-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slot',
            new_name='slug',
        ),
    ]
